### PR TITLE
Job creation page noobs

### PR DESCRIPTION
**Pull request by JonathanZeray**
Added progressbar and some styling to header of the "Jobs" page.

### CODE REVIEW

**Review by fdasabino — COMMENTED** [review]
I was wondering why we have installed antd icons when we already had react icons installed?

**Comment by fdasabino** [comment]
> why is line 40 to 48 commented out?

**Comment by paramighty** [comment]
> I was wondering why we have installed antd icons when we already had react icons installed?

> antD was used for the progress bar.

**Comment by JonathanZeray** [comment]
> I was wondering why we have installed antd icons when we already had react icons installed?

**Comment by JonathanZeray** [comment]
> why is line 40 to 48 commented out?

We had some issues with a form field that we tried inputting, dont want to delete it just yet.

**Pull request merged**
